version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  upstream:
    executor: base
    steps:
      - run: |
          mkdir -p ./certs
          echo "${mock_crt_pem}" > ./certs/mock.pem
      - run: wc -l ./certs/mock.pem
      - persist_workspace:
          root: certs
          paths:
            - mock.pem
  downstream:
    executor: base
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: wc -l /tmp/workspace/mock.pem

workflows:
  main:
    jobs:
      - upstream
      - downstream:
          requires:
            - upstream
